### ISSUE TITLE
复现GraphSMOTE(T)结果不理想

### ISSUE THREAD

**Issue by cheng-zhimin** [TianxiangZhao/GraphSmote#7]
你好，我想复现GraphSMOTE(T)的实验结果，我输入的命令行是：
python main.py --imbalance --no-cuda --dataset=cora --setting='recon' 
得到的结果如下：
ACC = 0.271, AUC-ROC = 0.5000, F Score = 0.1843
我试了很多次都没法得到论文中GraphSMOTE(T)的结果，请问是我的命令行错误了吗？还是我的操作存在其他问题，谢谢。

**Comment by TianxiangZhao** [comment]
你好 发现和上一个issue， issue 6, 内容一样，我直接在那里回答了 这里setting设置是只pretrain，并不会更新classifier
